In [1]:
%pip install pandas
import pandas as pd

car_sales_df = pd.read_csv('car-sales.csv')
car_sales_df.head()

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\gitapps\abasu1996\intelligentme\intelligentme\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [2]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")

In [3]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [4]:
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),inplace=True)
car_sales_missing

C:\Users\animb\AppData\Local\Temp\ipykernel_14484\3330876521.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),inplace=True)

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [5]:
car_sales_missing["Colour"].fillna("Black",inplace=True)
car_sales_missing

C:\Users\animb\AppData\Local\Temp\ipykernel_14484\1122597400.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing["Colour"].fillna("Black",inplace=True)

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda  Black   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [6]:
car_sales_missing.dropna(inplace=True)
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda  Black   92302.666667    4.0   $7,500

In [7]:
car_sales_missing.to_csv("car_sales_missing_dropped.csv")

Column from Series

In [8]:
seats_column = pd.Series([4,4,4,4])
seats_column

0    4
1    4
2    4
3    4
dtype: int64

In [9]:
car_sales_df["Seats"]=seats_column

In [10]:
car_sales_df

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    4.0
1   Honda    Red          87899      4   $5,000.00    4.0
2  Toyota   Blue          32549      3   $7,000.00    4.0
3     BMW  Black          11179      5  $22,000.00    4.0
4  Nissan  White         213095      4   $3,500.00    NaN
5  Toyota  Green          99213      4   $4,500.00    NaN
6   Honda   Blue          45698      4   $7,500.00    NaN
7   Honda   Blue          54738      4   $7,000.00    NaN
8  Toyota  White          60000      4   $6,250.00    NaN
9  Nissan  White          31600      4   $9,700.00    NaN

In [11]:
car_sales_df.fillna(5,inplace=True)

In [12]:
car_sales_df

     Make Colour  Odometer (KM)  Doors       Price  Seats
0  Toyota  White         150043      4   $4,000.00    4.0
1   Honda    Red          87899      4   $5,000.00    4.0
2  Toyota   Blue          32549      3   $7,000.00    4.0
3     BMW  Black          11179      5  $22,000.00    4.0
4  Nissan  White         213095      4   $3,500.00    5.0
5  Toyota  Green          99213      4   $4,500.00    5.0
6   Honda   Blue          45698      4   $7,500.00    5.0
7   Honda   Blue          54738      4   $7,000.00    5.0
8  Toyota  White          60000      4   $6,250.00    5.0
9  Nissan  White          31600      4   $9,700.00    5.0

Column from Python List

In [13]:
fuel_economy = [8.5,11,12,11.6,15,7.5,8,9,10,4.6]
car_sales_df["Fuel Economy per 100KM"] = fuel_economy

In [14]:
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6
4,Nissan,White,213095,4,"$3,500.00",5.0,15.0
5,Toyota,Green,99213,4,"$4,500.00",5.0,7.5
6,Honda,Blue,45698,4,"$7,500.00",5.0,8.0
7,Honda,Blue,54738,4,"$7,000.00",5.0,9.0
8,Toyota,White,60000,4,"$6,250.00",5.0,10.0
9,Nissan,White,31600,4,"$9,700.00",5.0,4.6

In [15]:
car_sales_df["Total Fuel Used (L)"] = car_sales_df["Fuel Economy per 100KM"] * car_sales_df["Odometer (KM)"] / 100
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used (L)
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764
4,Nissan,White,213095,4,"$3,500.00",5.0,15.0,31964.250
5,Toyota,Green,99213,4,"$4,500.00",5.0,7.5,7440.975
6,Honda,Blue,45698,4,"$7,500.00",5.0,8.0,3655.840
7,Honda,Blue,54738,4,"$7,000.00",5.0,9.0,4926.420
8,Toyota,White,60000,4,"$6,250.00",5.0,10.0,6000.000
9,Nissan,White,31600,4,"$9,700.00",5.0,4.6,1453.600

In [16]:
Markdown("Column from another column")

NameError: name 'Markdown' is not defined

In [ ]:
car_sales_df["Number of Wheels"] = 4
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Total Fuel Used (L),Number of Wheels
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,12753.655,4
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,9668.890,4
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,3905.880,4
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,1296.764,4
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,31964.250,4
5,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,7440.975,4
6,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,3655.840,4
7,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4926.420,4
8,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,6000.000,4
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,1453.600,4

In [ ]:
car_sales_df["Passed Road Safety"] = True
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Total Fuel Used (L),Number of Wheels,Passed Road Safety
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,12753.655,4,True
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,9668.890,4,True
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,3905.880,4,True
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,1296.764,4,True
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,31964.250,4,True
5,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,7440.975,4,True
6,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,3655.840,4,True
7,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4926.420,4,True
8,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,6000.000,4,True
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,1453.600,4,True

In [ ]:
car_sales_df.dtypes

Make                       object
Colour                     object
Odometer (KM)               int64
Doors                       int64
Price                      object
Seats                      object
Fuel Economy per 100KM    float64
Total Fuel Used           float64
Total Fuel Used (L)       float64
Number of Wheels            int64
Passed Road Safety           bool
dtype: object

In [ ]:
car_sales_df.drop("Total Fuel Used (L)", axis=1, inplace=True)
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Number of Wheels,Passed Road Safety
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,4,True
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,4,True
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,4,True
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,4,True
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,4,True
5,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,4,True
6,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,4,True
7,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4,True
8,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,4,True
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,4,True

In [ ]:
car_sales_missing.sample(frac=1)

     Make Colour       Odometer  Doors    Price
6   Honda  Black   92302.666667    4.0   $7,500
4  Nissan  White  213095.000000    4.0   $3,500
0  Toyota  White  150043.000000    4.0   $4,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
5  Toyota  Green   92302.666667    4.0   $4,500
1   Honda    Red   87899.000000    4.0   $5,000

In [ ]:
car_sales_df.sample(frac=1,inplace=True)

TypeError: NDFrame.sample() got an unexpected keyword argument 'inplace'. Did you mean 'replace'?

In [ ]:
 car_sales_suffled = car_sales_df.sample(frac=1)

In [ ]:
car_sales_suffled

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Number of Wheels,Passed Road Safety
5,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,4,True
7,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4,True
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,4,True
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,4,True
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,4,True
6,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,4,True
8,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,4,True
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,4,True
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,4,True
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,4,True

In [ ]:
car_sales_suffled.sample(frac=0.001)

Empty DataFrame
Columns: [Make, Colour, Odometer (KM), Doors, Price, Seats, Fuel Economy per 100KM, Total Fuel Used, Number of Wheels, Passed Road Safety]
Index: []

In [ ]:
car_sales_reset_index = car_sales_suffled.reset_index(drop=True)
car_sales_reset_index

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Number of Wheels,Passed Road Safety
0,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,4,True
1,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4,True
2,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,4,True
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,4,True
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,4,True
5,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,4,True
6,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,4,True
7,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,4,True
8,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,4,True
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,4,True

In [ ]:
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Number of Wheels,Passed Road Safety
0,Toyota,White,150043,4,"$4,000.00",4.0,8.5,12753.655,4,True
1,Honda,Red,87899,4,"$5,000.00",4.0,11.0,9668.890,4,True
2,Toyota,Blue,32549,3,"$7,000.00",4.0,12.0,3905.880,4,True
3,BMW,Black,11179,5,"$22,000.00",4.0,11.6,1296.764,4,True
4,Nissan,White,213095,4,"$3,500.00",5,15.0,31964.250,4,True
5,Toyota,Green,99213,4,"$4,500.00",5,7.5,7440.975,4,True
6,Honda,Blue,45698,4,"$7,500.00",5,8.0,3655.840,4,True
7,Honda,Blue,54738,4,"$7,000.00",5,9.0,4926.420,4,True
8,Toyota,White,60000,4,"$6,250.00",5,10.0,6000.000,4,True
9,Nissan,White,31600,4,"$9,700.00",5,4.6,1453.600,4,True

In [ ]:
car_sales_df["Odometer (KM)"] = car_sales_df["Odometer (KM)"].apply(lambda x: x/1.6)

In [ ]:
car_sales_df

,Make,Colour,Odometer (KM),Doors,Price,Seats,Fuel Economy per 100KM,Total Fuel Used,Number of Wheels,Passed Road Safety
0,Toyota,White,93776.875,4,"$4,000.00",4.0,8.5,12753.655,4,True
1,Honda,Red,54936.875,4,"$5,000.00",4.0,11.0,9668.890,4,True
2,Toyota,Blue,20343.125,3,"$7,000.00",4.0,12.0,3905.880,4,True
3,BMW,Black,6986.875,5,"$22,000.00",4.0,11.6,1296.764,4,True
4,Nissan,White,133184.375,4,"$3,500.00",5,15.0,31964.250,4,True
5,Toyota,Green,62008.125,4,"$4,500.00",5,7.5,7440.975,4,True
6,Honda,Blue,28561.250,4,"$7,500.00",5,8.0,3655.840,4,True
7,Honda,Blue,34211.250,4,"$7,000.00",5,9.0,4926.420,4,True
8,Toyota,White,37500.000,4,"$6,250.00",5,10.0,6000.000,4,True
9,Nissan,White,19750.000,4,"$9,700.00",5,4.6,1453.600,4,True